// ============================================================================
// File: wb_vga.sv
// Author: Chris Kane-Pardy, Niklas Anderson, Jacob Burtenshaw
// Date Created: May 4th 2026
// Description: Wishbone VGA peripheral for 640x480 display. Implements a
//              scan-line sprite engine supporting up to 32 simultaneously
//              visible sprites using a unified Vivado BRAM ROM. Sprites may
//              be 32x32 (sprite_type=0) or 16x16 (sprite_type=1). The unified
//              sprite_rom contains both bigfont glyphs (IDs 0-94) and guitar
//              sprites (IDs 95-111) generated by gen_sprites_coe.py. A
//              scanline prefetch FSM time-multiplexes the single-port ROM
//              during H-blanking to load all 32 sprite row bitmaps. The
//              separate font_rom text overlay has been removed; all rendering
//              goes through the unified sprite engine.
// AI Contributions: Copilot (claude-sonnet-4.6) implemented the
//                   sprite engine scanline prefetch FSM, 2-layer pixel
//                   compositor, extended Wishbone register map, and Phase 2
//                   unification of font and sprite ROMs. Copilot also
//                   performed BRAM timing analysis and HDL review.
// ============================================================================

module wb_vga (
    input  logic        wb_clk_i,
    input  logic        wb_rst_i,

    input  logic [11:0] wb_adr_i,
    input  logic [31:0] wb_dat_i,
    input  logic [3:0]  wb_sel_i,
    input  logic        wb_we_i,
    input  logic        wb_cyc_i,
    input  logic        wb_stb_i,

    output logic [31:0] wb_dat_o,
    output logic        wb_ack_o,

    output logic        vga_hsync,
    output logic        vga_vsync,
    output logic [3:0]  vga_red,
    output logic [3:0]  vga_green,
    output logic [3:0]  vga_blue
);

    //---------------------------------------------------------
    // Display parameters
    //---------------------------------------------------------
    localparam int ACTIVE_COLS = 640;
    localparam int ACTIVE_ROWS = 480;
    localparam int SPRITE_SIZE = 32;
    localparam int N_SPRITES   = 32;

    //---------------------------------------------------------
    // Register map  (reg_sel = wb_adr_i[11:2])
    //
    //   Word  5  0x014  REG_BG_COLOR — [11:8]=R [7:4]=G [3:0]=B
    //   Word 32+n*2  0x080+n*8  SPRITE_POS[n] — [19:10]=y_pos [9:0]=x_pos
    //   Word 33+n*2  0x084+n*8  SPRITE_CFG[n] — [31:25]=sprite_id (7-bit)
    //                                            [15:12]=R [11:8]=G [7:4]=B
    //                                            [1]=sprite_type (0=32x32, 1=16x16)
    //                                            [0]=visible
    //---------------------------------------------------------
    localparam logic [9:0] REG_BG_COLOR = 10'd5;

    logic [9:0] reg_sel;
    logic       wb_access;
    logic [4:0] spr_idx;      // sprite index, valid when is_sprite_reg
    logic       spr_is_cfg;   // 0 = POS word, 1 = CFG word
    logic       is_sprite_reg;

    assign reg_sel       = wb_adr_i[11:2];
    assign wb_access     = wb_cyc_i && wb_stb_i;
    // reg_sel[6:1] in range 16..47 for sprites 0..31; subtract 16 to get index
    assign spr_idx       = reg_sel[6:1] - 5'd16;
    assign spr_is_cfg    = reg_sel[0];
    assign is_sprite_reg = (reg_sel >= 10'd32) && (reg_sel <= 10'd95);

    //---------------------------------------------------------
    // VGA timing
    //---------------------------------------------------------
    logic        video_on;
    logic [11:0] pixel_row;
    logic [11:0] pixel_col;

    dtg u_dtg (
        .clock        (wb_clk_i),
        .rst          (wb_rst_i),
        .horiz_sync   (vga_hsync),
        .vert_sync    (vga_vsync),
        .video_on     (video_on),
        .pixel_row    (pixel_row),
        .pixel_column (pixel_col)
    );

 
    //---------------------------------------------------------
    // Sprite ROM
    //   Vivado Block Memory Generator: Single Port ROM, 32-bit x 4096,
    //   no output register (1-cycle read latency), init: guitarSprites.coe.
    //   Address layout: {sprite_id[6:0], row_offset[4:0]}
    //---------------------------------------------------------
    logic [11:0] sprite_rom_addr;
    logic [31:0] sprite_rom_data;

    sprite_rom u_sprite_rom (
        .clka  (wb_clk_i),
        .addra (sprite_rom_addr),
        .douta (sprite_rom_data)
    );

    //---------------------------------------------------------
    // CPU-visible registers
    //---------------------------------------------------------
    logic [11:0] bg_color_reg;              // [11:8]=R [7:4]=G [3:0]=B

    // Sprite descriptors (plain registers, ~512 FFs)
    logic [31:0] sprite_pos [0:N_SPRITES-1]; // [19:10]=y_pos  [9:0]=x_pos
    // [31:25]=sprite_id(7b) [15:12]=R [11:8]=G [7:4]=B [1]=sprite_type [0]=visible
    logic [31:0] sprite_cfg [0:N_SPRITES-1];

    //---------------------------------------------------------
    // Wishbone writes
    //---------------------------------------------------------
    always_ff @(posedge wb_clk_i) begin
        if (wb_rst_i) begin
            wb_ack_o     <= 1'b0;
            bg_color_reg <= 12'h000;
            for (int i = 0; i < N_SPRITES; i++) begin
                sprite_pos[i] <= 32'd0;
                sprite_cfg[i] <= 32'd0;
            end
        end else begin
            wb_ack_o <= wb_access && !wb_ack_o;

            if (wb_access && wb_we_i && !wb_ack_o) begin
                if (is_sprite_reg) begin
                    if (!spr_is_cfg)
                        sprite_pos[spr_idx] <= wb_dat_i;
                    else
                        sprite_cfg[spr_idx] <= wb_dat_i;
                end else begin
                    unique case (reg_sel)
                        REG_BG_COLOR: bg_color_reg <= wb_dat_i[11:0];
                        default: ;
                    endcase
                end
            end
        end
    end

    //---------------------------------------------------------
    // Wishbone reads
    //---------------------------------------------------------
    always_comb begin
        if (is_sprite_reg) begin
            wb_dat_o = spr_is_cfg ? sprite_cfg[spr_idx] : sprite_pos[spr_idx];
        end else begin
            unique case (reg_sel)
                REG_BG_COLOR: wb_dat_o = {20'd0, bg_color_reg};
                default:      wb_dat_o = 32'h00000000;
            endcase
        end
    end
    
    /*

    //---------------------------------------------------------
    // Scanline prefetch FSM
    //
    // At the first H-blank clock each active row (pixel_col == ACTIVE_COLS),
    // the FSM time-multiplexes the sprite ROM to prefetch row bitmaps for
    // the NEXT scan line into sprite_row_bits[].
    //
    // Timing (1-cycle BRAM read latency, no output register):
    //   Cycle 0 : present ROM address for sprite 0
    //   Cycle 1 : present addr sprite 1; capture sprite_row_bits[0]
    //   ...
    //   Cycle 31: present addr sprite 31; capture sprite_row_bits[30]
    //   Cycle 32: idle addr; capture sprite_row_bits[31]
    //   Cycle 33: done — fetch_active deasserted
    //
    // 33 cycles used; ~160 H-blank cycles available per row.
    //---------------------------------------------------------
    logic [5:0]  fetch_cnt;
    logic        fetch_active;
    logic [31:0] sprite_row_bits   [0:N_SPRITES-1]; // 1bpp row bitmaps, bit31=leftmost
    logic        sprite_row_active [0:N_SPRITES-1]; // sprite overlaps this scan line

    // Row to prefetch: pixel_row + 1, wrapping at ACTIVE_ROWS-1 → 0
    logic [9:0] prefetch_row;
    always_comb begin
        prefetch_row = (pixel_row[9:0] == 10'(ACTIVE_ROWS - 1))
                       ? 10'd0
                       : pixel_row[9:0] + 10'd1;
    end

    // Sprite ROM address driven by FSM counter
    always_comb begin
        if (fetch_active && (fetch_cnt < 6'd32))
            sprite_rom_addr = {
                sprite_cfg[fetch_cnt[4:0]][31:25],
                5'(prefetch_row - sprite_pos[fetch_cnt[4:0]][19:10])
            };
        else
            sprite_rom_addr = 12'd0;
    end

    // Intermediate signals for the capture side (sprite fetch_cnt-1)
    logic [4:0] cap_si;     // index of sprite whose ROM data just arrived
    logic [9:0] cap_yp;     // y_pos of that sprite
    logic       cap_in_row; // sprite overlaps prefetch_row

    assign cap_si     = fetch_cnt[4:0] - 5'd1; // wraps 0→31 at fetch_cnt=32 ✓
    assign cap_yp     = sprite_pos[cap_si][19:10];
    assign cap_in_row = sprite_cfg[cap_si][0] &&
                        (prefetch_row >= cap_yp) &&
                        (prefetch_row <  cap_yp +
                            (sprite_cfg[cap_si][1] ? 10'd16 : 10'(SPRITE_SIZE)));

    always_ff @(posedge wb_clk_i) begin
        if (wb_rst_i) begin
            fetch_active <= 1'b0;
            fetch_cnt    <= 6'd0;
            for (int i = 0; i < N_SPRITES; i++) begin
                sprite_row_bits[i]   <= 32'd0;
                sprite_row_active[i] <= 1'b0;
            end
        end else begin
            // Trigger once per active row at the first H-blank clock
            if (!fetch_active &&
                (pixel_col == 12'(ACTIVE_COLS)) &&
                (pixel_row[9:0] < 10'(ACTIVE_ROWS))) begin
                fetch_active <= 1'b1;
                fetch_cnt    <= 6'd0;
            end

            if (fetch_active) begin
                if (fetch_cnt <= 6'd32) begin
                    // Capture ROM data for sprite cap_si (one cycle behind address)
                    if (fetch_cnt > 6'd0) begin
                        sprite_row_active[cap_si] <= cap_in_row;
                        sprite_row_bits[cap_si]   <= cap_in_row ? sprite_rom_data : 32'd0;
                    end
                    fetch_cnt <= fetch_cnt + 6'd1;
                end else begin
                    fetch_active <= 1'b0;
                end
            end
        end
    end

    //---------------------------------------------------------
    // Per-sprite horizontal offset (combinational)
    // pixel_col - x_pos underflows for columns left of the sprite,
    // producing a value >= SPRITE_SIZE that the compositor rejects.
    //---------------------------------------------------------
    logic [11:0] sprite_col_offset [0:N_SPRITES-1];
    genvar gi;
    generate
        for (gi = 0; gi < N_SPRITES; gi++) begin : gen_col_off
            assign sprite_col_offset[gi] = pixel_col - {2'd0, sprite_pos[gi][9:0]};
        end
    endgenerate

    //---------------------------------------------------------
    // 2-Layer pixel compositor (combinational)
    //
    //   Layer 1 (bottom): bg_color_reg
    //   Layer 2:          sprite engine — sprite 0 has highest priority
    //                     (iterated high→low so index 0 is applied last)
    //
    // Sprite bit 31 = leftmost pixel (guitarSprites.coe convention).
    // A sprite 0-bit is transparent; only 1-bits paint the fg_color.
    // sprite_type=0 → 32×32 (check col_offset < 32)
    // sprite_type=1 → 16×16 (check col_offset < 16; bitmap in bits 31..16)
    //---------------------------------------------------------
    logic [11:0] pixel_color; // {R[3:0], G[3:0], B[3:0]}

    always_comb begin
        // Layer 1: background color
        pixel_color = bg_color_reg;

        // Layer 2: sprites (high index first; index 0 written last = wins)
        for (int s = N_SPRITES-1; s >= 0; s--) begin
            if (sprite_row_active[s] &&
                video_on &&
                (sprite_col_offset[s] < (sprite_cfg[s][1] ? 12'd16 : 12'(SPRITE_SIZE))) &&
                sprite_row_bits[s][31 - sprite_col_offset[s][4:0]]) begin
                pixel_color = sprite_cfg[s][15:4]; // {R[15:12], G[11:8], B[7:4]}
            end
        end
    end

    //---------------------------------------------------------
    // VGA output
    //---------------------------------------------------------
    always_comb begin
        if (!video_on) begin
            vga_red   = 4'h0;
            vga_green = 4'h0;
            vga_blue  = 4'h0;
        end else begin
            vga_red   = pixel_color[11:8];
            vga_green = pixel_color[7:4];
            vga_blue  = pixel_color[3:0];
        end
    end
    */

endmodule
